import { PlansRow, SubscriptionPlan } from "types";
import { env } from "@/env.mjs";

export const pricingData: SubscriptionPlan[] = [
  {
    title: "Starter",
    description: "For growing businesses",
    benefits: [
      "1,000 AI conversations/month",
      "1 website",
      "1 document upload",
      "Basic customization",
      "Email transcript export",
      "Basic chat widget",
      "Basic analytics",
      "Standard support",
      "Overage purchases available",
    ],
    limitations: [
      "No custom branding",
      "No integrations",
      "No agent handoff",
      "Limited to 1 site",
    ],
    prices: {
      monthly: 15,
      yearly: 144,
    },
    stripeIds: {
      monthly: env.NEXT_PUBLIC_STRIPE_STARTER_MONTHLY_PLAN_ID,
      yearly: env.NEXT_PUBLIC_STRIPE_STARTER_YEARLY_PLAN_ID,
    },
  },
  {
    title: "Pro",
    description: "For established teams",
    benefits: [
      "5,000 AI conversations/month",
      "3 websites",
      "5 document uploads",
      "Custom branding",
      "Analytics",
      "Agent handoff",
      "External integrations",
      "Custom chat widget",
      "Workflow automation",
      "Priority support",
      "Overage purchases available",
    ],
    limitations: [
      "No advanced analytics",
      "No automation triggers",
      "No SMS/email follow-ups",
    ],
    prices: {
      monthly: 39,
      yearly: 374,
    },
    stripeIds: {
      monthly: env.NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PLAN_ID,
      yearly: env.NEXT_PUBLIC_STRIPE_PRO_YEARLY_PLAN_ID,
    },
  },
  {
    title: "Vertical Pro",
    description: "For industry specialists",
    benefits: [
      "20,000 AI conversations/month",
      "Unlimited websites",
      "20 document uploads",
      "Industry templates",
      "Advanced analytics",
      "Agent handoff",
      "Automation triggers",
      "SMS/email follow-ups",
      "Custom chat widget",
      "Advanced workflow automation",
      "Priority support",
      "Overage purchases available",
    ],
    limitations: [
      "No white-labeling",
      "No SLAs",
      "No custom integrations",
    ],
    prices: {
      monthly: 79,
      yearly: 758,
    },
    stripeIds: {
      monthly: env.NEXT_PUBLIC_STRIPE_VERTICAL_PRO_MONTHLY_PLAN_ID,
      yearly: env.NEXT_PUBLIC_STRIPE_VERTICAL_PRO_YEARLY_PLAN_ID,
    },
  },
  {
    title: "Enterprise",
    description: "For large organizations",
    benefits: [
      "75,000+ AI conversations/month",
      "White-labeling",
      "SLAs",
      "API access",
      "Agent handoff",
      "Custom integrations",
      "Compliance logging",
      "Custom chat widget",
      "24/7 priority support",
      "Custom pricing",
    ],
    limitations: [],
    prices: {
      monthly: 249,
      yearly: 2390,
    },
    stripeIds: {
      monthly: env.NEXT_PUBLIC_STRIPE_ENTERPRISE_MONTHLY_PLAN_ID,
      yearly: env.NEXT_PUBLIC_STRIPE_ENTERPRISE_YEARLY_PLAN_ID,
    },
  },
];

export const plansColumns = [
  "starter",
  "pro",
  "vertical-pro",
  "enterprise",
] as const;

export const comparePlans: PlansRow[] = [
  {
    feature: "Monthly AI Conversations",
    starter: "1,000",
    pro: "5,000",
    "vertical-pro": "20,000",
    enterprise: "75,000+",
  },
  {
    feature: "Websites",
    starter: "1",
    pro: "3",
    "vertical-pro": "Unlimited",
    enterprise: "Unlimited",
  },
  {
    feature: "Document Uploads",
    starter: "1",
    pro: "5",
    "vertical-pro": "20",
    enterprise: "Unlimited",
  },
  {
    feature: "Custom Branding",
    starter: null,
    pro: true,
    "vertical-pro": true,
    enterprise: true,
  },
  {
    feature: "Analytics",
    starter: "Basic",
    pro: true,
    "vertical-pro": "Advanced",
    enterprise: "Custom",
  },
  {
    feature: "Agent Handoff",
    starter: null,
    pro: true,
    "vertical-pro": true,
    enterprise: true,
  },
  {
    feature: "Integrations",
    starter: null,
    pro: "External",
    "vertical-pro": "Advanced",
    enterprise: "Custom",
  },
  {
    feature: "Automation Triggers",
    starter: null,
    pro: null,
    "vertical-pro": true,
    enterprise: true,
  },
  {
    feature: "SMS/Email Follow-ups",
    starter: null,
    pro: null,
    "vertical-pro": true,
    enterprise: true,
  },
  {
    feature: "Industry Templates",
    starter: null,
    pro: null,
    "vertical-pro": true,
    enterprise: true,
  },
  {
    feature: "White-labeling",
    starter: null,
    pro: null,
    "vertical-pro": null,
    enterprise: true,
  },
  {
    feature: "API Access",
    starter: null,
    pro: null,
    "vertical-pro": null,
    enterprise: true,
  },
  {
    feature: "SLAs",
    starter: null,
    pro: null,
    "vertical-pro": null,
    enterprise: true,
  },
  {
    feature: "Support",
    starter: "Email",
    pro: "Priority",
    "vertical-pro": "Priority",
    enterprise: "24/7",
  },
  {
    feature: "Chat Widget",
    starter: "Basic",
    pro: "Custom",
    "vertical-pro": "Custom",
    enterprise: "Custom",
  },
  {
    feature: "Workflow Automation",
    starter: null,
    pro: true,
    "vertical-pro": "Advanced",
    enterprise: "Custom",
  },
  {
    feature: "Overage Pricing",
    starter: "$5/1K messages",
    pro: "$5/1K messages",
    "vertical-pro": "$5/1K messages",
    enterprise: "Custom",
  },
];
